name: Documentation Hosting Pipeline

on:
  push:
    branches:
      - '**'         # Trigger the action on every commit to any branch


permissions:
  id-token: write    # Required for requesting the OIDC token
  contents: write
  issues: write
  pull-requests: write

env:
  AWS_REGION: us-east-1  # Change to your AWS Region

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::360029684926:role/S3_alkira_staging_access
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify caller identity (debug step)
        run: aws sts get-caller-identity

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install sphinx==5.0.0
      - name: Build Sphinx Docs
        run: |
          sphinx-build -b html source/ source/build
      - name: Upload to S3 using AWS CLI
        run: |
          aws s3 sync source/build s3://${{ secrets.AWS_S3_BUCKET }} --delete